-- ChatCommander Constants

local constants = {

    spawn_aliases = {
        ["airportbus"]="airbus",
        ["ro86alkonost"]="alkonost",
        ["annihilatorstealth"]="annihilator2",
        ["armytrailer"]="armytanker",
        ["astroncustom"]="astron2",
        ["ballerle"]="baller3",
        ["ballerlelwb"]="baller4",
        ["ballerlearmored"]="baller5",
        ["ballerlelwbarmored"]="baller6",
        ["ballerst"]="baller7",
        ["banshee900r"]="banshee2",
        ["barrackssemi"]="barracks2",
        ["bati801"]="bati",
        ["bati801rr"]="bati2",
        ["injection"]="bfinjection",
        ["beejayxl"]="bjxl",
        ["blazerlifeguard"]="blazer2",
        ["hotrodblazer"]="blazer3",
        ["streetblazer"]="blazer4",
        ["blazeraqua"]="blazer5",
        ["atomicblimp"]="blimp",
        ["xeroblimp"]="blimp2",
        ["blimp"]="blimp3",
        ["blistacompact"]="blista2",
        ["gogomonkeyblista"]="blista3",
        ["bodhi"]="bodhi2",
        ["rm10bombushka"]="bombushka",
        ["armoredboxville"]="boxville5",
        ["brickade6x6"]="brickade2",
        ["brioso300"]="brioso2",
        ["brioso300widebody"]="brioso3",
        ["apocalypsebruiser"]="bruiser",
        ["futureshockbruiser"]="bruiser2",
        ["nightmarebruiser"]="bruiser3",
        ["apocalypsebrutus"]="brutus",
        ["futureshockbrutus"]="brutus2",
        ["nightmarebrutus"]="brutus3",
        ["roosevelt"]="btype",
        ["frankenstange"]="btype2",
        ["rooseveltvalor"]="btype3",
        ["buccaneercustom"]="buccaneer2",
        ["buffalos"]="buffalo2",
        ["sprunkbuffalo"]="buffalo3",
        ["buffalostx"]="buffalo4",
        ["dozer"]="bulldozer",
        ["calicogtf"]="calico",
        ["caracara4x4"]="caracara2",
        ["apocalypsecerberus"]="cerberus",
        ["futureshockcerberus"]="cerberus2",
        ["nightmarecerberus"]="cerberus3",
        ["cheetahclassic"]="cheetah2",
        ["chinocustom"]="chino2",
        ["dashound"]="coach",
        ["cognoscenti55"]="cog55",
        ["cognoscenti55armored"]="cog552",
        ["cognoscenticabrio"]="cogcabrio",
        ["cognoscentiarmored"]="cognoscenti2",
        ["comet"]="comet2",
        ["cometretrocustom"]="comet3",
        ["cometsafari"]="comet4",
        ["cometsr"]="comet5",
        ["comets2"]="comet6",
        ["comets2cabrio"]="comet7",
        ["coquetteclassic"]="coquette2",
        ["coquetteblackfin"]="coquette3",
        ["coquetted10"]="coquette4",
        ["cycloneii"]="cyclone2",
        ["apocalypsedeathbike"]="deathbike",
        ["futureshockdeathbike"]="deathbike2",
        ["nightmaredeathbike"]="deathbike3",
        ["devesteeight"]="deveste",
        ["diabolus"]="diablous",
        ["diaboluscustom"]="diablous2",
        ["weaponizeddinghy"]="dinghy5",
        ["duneloader"]="dloader",
        ["pisswasserdominator"]="dominator2",
        ["dominatorgtx"]="dominator3",
        ["apocalypsedominator"]="dominator4",
        ["futureshockdominator"]="dominator5",
        ["nightmaredominator"]="dominator6",
        ["dominatorasp"]="dominator7",
        ["dominatorgtt"]="dominator8",
        ["doublet"]="double",
        ["8fdrafter"]="drafter",
        ["dubsta6x6"]="dubsta3",
        ["dukeodeath"]="dukes2",
        ["beaterdukes"]="dukes3",
        ["dunebuggy"]="dune",
        ["spacedocker"]="dune2",
        ["dunefav"]="dune3",
        ["rampbuggy"]="dune4",
        ["elegyretrocustom"]="elegy",
        ["elegyrh8"]="elegy2",
        ["entityxxr"]="entity2",
        ["entitymt"]="entity3",
        ["hotringeveron"]="everon2",
        ["factioncustom"]="faction2",
        ["factioncustomdonk"]="faction3",
        ["faggiosport"]="faggio",
        ["faggio"]="faggio2",
        ["faggiomod"]="faggio3",
        ["fib"]="fbi",
        ["fcr1000"]="fcr",
        ["fcr1000custom"]="fcr2",
        ["felongt"]="felon2",
        ["feltzer"]="feltzer2",
        ["stirlinggt"]="feltzer3",
        ["firetruck"]="firetruk",
        ["pr4"]="formula",
        ["r88"]="formula2",
        ["freighttrain"]="freight",
        ["futogtx"]="futo2",
        ["redwoodgauntlet"]="gauntlet2",
        ["gauntletclassic"]="gauntlet3",
        ["gauntlethellfire"]="gauntlet4",
        ["gauntletclassiccustom"]="gauntlet5",
        ["gangburrito"]="gburrito",
        ["glendalecustom"]="glendale2",
        ["granger3600lx"]="granger2",
        ["hakuchoudrag"]="hakuchou2",
        ["dockhandler"]="handler",
        ["haulercustom"]="hauler2",
        ["hotringsabre"]="hotring",
        ["howardnx25"]="howard",
        ["fh1hunter"]="hunter",
        ["huntleys"]="huntley",
        ["weaponizedignus"]="ignus2",
        ["apocalypseimpaler"]="impaler2",
        ["futureshockimpaler"]="impaler3",
        ["nightmareimpaler"]="impaler4",
        ["apocalypseimperator"]="imperator",
        ["futureshockimperator"]="imperator2",
        ["nightmareimperator"]="imperator3",
        ["infernusclassic"]="infernus2",
        ["insurgentpickup"]="insurgent",
        ["insurgent"]="insurgent2",
        ["insurgentpickupcustom"]="insurgent3",
        ["issi"]="issi2",
        ["issiclassic"]="issi3",
        ["apocalypseissi"]="issi4",
        ["futureshockissi"]="issi5",
        ["nightmareissi"]="issi6",
        ["issisport"]="issi7",
        ["issirally"]="issi8",
        ["italigtbcustom"]="italigtb2",
        ["jb700w"]="jb7002",
        ["jesterracecar"]="jester2",
        ["jesterclassic"]="jester3",
        ["jesterrr"]="jester4",
        ["journeyii"]="journey2",
        ["blistakanjo"]="kanjo",
        ["tm02khanjali"]="khanjali",
        ["kurumaarmored"]="kuruma2",
        ["landstalkerxl"]="landstalker2",
        ["p996lazer"]="lazer",
        ["re7b"]="le7b",
        ["lifeguard"]="lguard",
        ["turretedlimo"]="limo2",
        ["luxordeluxe"]="luxor2",
        ["mananacustom"]="manana2",
        ["manchezscout"]="manchez2",
        ["manchezscoutc"]="manchez3",
        ["massacroracecar"]="massacro2",
        ["michelligt"]="michelli",
        ["ultralight"]="microlight",
        ["invadeandpersuadetank"]="minitank",
        ["minivancustom"]="minivan2",
        ["v65molotok"]="molotok",
        ["apocalypsesasquatch"]="monster3",
        ["futureshocksasquatch"]="monster4",
        ["nightmaresasquatch"]="monster5",
        ["moonbeamcustom"]="moonbeam2",
        ["lawnmower"]="mower",
        ["mulecustom"]="mule4",
        ["nebulaturbo"]="nebula",
        ["nerocustom"]="nero2",
        ["9f"]="ninef",
        ["9fcabrio"]="ninef2",
        ["p45nokota"]="nokota",
        ["br8"]="openwheel1",
        ["dr1"]="openwheel2",
        ["oppressormkii"]="oppressor2",
        ["oraclexs"]="oracle",
        ["oracle"]="oracle2",
        ["paragonr"]="paragon",
        ["paragonrarmored"]="paragon2",
        ["patriotstretch"]="patriot2",
        ["patriotmilspec"]="patriot3",
        ["kurtz31patrolboat"]="patrolboat",
        ["policeprisonbus"]="pbus",
        ["festivalbus"]="pbus2",
        ["pcj600"]="pcj",
        ["penumbraff"]="penumbra2",
        ["peyotegasser"]="peyote2",
        ["peyotecustom"]="peyote3",
        ["811"]="pfister811",
        ["phantomwedge"]="phantom2",
        ["phantomcustom"]="phantom3",
        ["policecruiser"]="police",
        ["unmarkedcruiser"]="police4",
        ["policebike"]="policeb",
        ["policerancher"]="policeold1",
        ["policeroadcruiser"]="policeold2",
        ["policetransporter"]="policet",
        ["policemaverick"]="polmav",
        ["poundercustom"]="pounder2",
        ["parkranger"]="pranger",
        ["policepredator"]="predator",
        ["primocustom"]="primo2",
        ["x80proto"]="prototipo",
        ["300r"]="r300",
        ["radius"]="radi",
        ["trailer"]="raketrailer",
        ["dune"]="rallytruck",
        ["rapidgtclassic"]="rapidgt3",
        ["rattruck"]="ratloader2",
        ["rustyrebel"]="rebel",
        ["rebel"]="rebel2",
        ["reblagts"]="rebla",
        ["rentalshuttlebus"]="rentalbus",
        ["retinuemkii"]="retinue2",
        ["rhinotank"]="rhino",
        ["policeriot"]="riot",
        ["rcv"]="riot2",
        ["romerohearse"]="romero",
        ["rampantrocket"]="rrocket",
        ["ruiner2000"]="ruiner2",
        ["ruinerzz8"]="ruiner4",
        ["rumpocustom"]="rumpo3",
        ["s80rr"]="s80",
        ["sabreturbo"]="sabregt",
        ["sabreturbocustom"]="sabregt2",
        ["sanchez"]="sanchez2",
        ["sandkingxl"]="sandking",
        ["sandkingswb"]="sandking2",
        ["apocalypsescarab"]="scarab",
        ["futureshockscarab"]="scarab2",
        ["nightmarescarab"]="scarab3",
        ["schafter"]="schafter2",
        ["schafterv12"]="schafter3",
        ["schafterlwb"]="schafter4",
        ["schafterv12armored"]="schafter5",
        ["schafterlwbarmored"]="schafter6",
        ["schlagengt"]="schlagen",
        ["schwartzer"]="schwarzer",
        ["scraptruck"]="scrap",
        ["sparrow"]="seasparrow2",
        ["seminolefrontier"]="seminole2",
        ["sentinelxs"]="sentinel",
        ["sentinel"]="sentinel2",
        ["sentinelclassicwidebody"]="sentinel4",
        ["etr1"]="sheava",
        ["sheriffcruiser"]="sheriff",
        ["sheriffsuv"]="sheriff2",
        ["lostslamvan"]="slamvan2",
        ["slamvancustom"]="slamvan3",
        ["apocalypseslamvan"]="slamvan4",
        ["futureshockslamvan"]="slamvan5",
        ["nightmareslamvan"]="slamvan6",
        ["spectercustom"]="specter2",
        ["clownvan"]="speedo2",
        ["speedocustom"]="speedo4",
        ["stallion"]="stalion",
        ["burgershotstallion"]="stalion2",
        ["lf22starling"]="starling",
        ["b11strikeforce"]="strikeforce",
        ["mallard"]="stunt",
        ["kraken"]="submersible2",
        ["sultanclassic"]="sultan2",
        ["sultanrsclassic"]="sultan3",
        ["superdiamond"]="superd",
        ["supervolitocarbon"]="supervolito2",
        ["surfercustom"]="surfer3",
        ["swiftdeluxe"]="swift2",
        ["tacovan"]="taco",
        ["tahomacoupe"]="tahoma",
        ["tailgaters"]="tailgater2",
        ["drifttampa"]="tampa2",
        ["weaponizedtampa"]="tampa3",
        ["technicalaqua"]="technical2",
        ["technicalcustom"]="technical3",
        ["10f"]="tenf",
        ["10fwidebody"]="tenf2",
        ["terrorbyte"]="terbyte",
        ["tipper"]="tiptruck",
        ["toreroxo"]="torero2",
        ["tornadocustom"]="tornado5",
        ["tornadoratrod"]="tornado6",
        ["fieldmaster"]="tractor2",
        ["mobileoperationscenter"]="trailerlarge",
        ["aagun"]="trailersmall2",
        ["antiair"]="trailersmall2",
        ["antiaircrafttrailer"]="trailersmall2",
        ["trashmaster"]="trash",
        ["whippetracebike"]="tribike",
        ["endurexracebike"]="tribike2",
        ["tricyclesracebike"]="tribike3",
        ["desertraid"]="trophytruck2",
        ["troposrallye"]="tropos",
        ["tulipm100"]="tulip2",
        ["turismoclassic"]="turismo2",
        ["utilitytruck"]="utillitruck",
        ["valkyriemod.0"]="valkyrie2",
        ["velum5seater"]="velum2",
        ["verlierer"]="verlierer2",
        ["vetoclassic"]="veto",
        ["vetomodern"]="veto2",
        ["vigerozx"]="vigero2",
        ["virgoclassiccustom"]="virgo2",
        ["virgoclassic"]="virgo3",
        ["rocketvoltic"]="voltic2",
        ["voodoocustom"]="voodoo",
        ["voodoo"]="voodoo2",
        ["warrenerhkr"]="warrener2",
        ["weevilcustom"]="weevil2",
        ["windsordrop"]="windsor2",
        ["xlsarmored"]="xls2",
        ["driftyosemite"]="yosemite2",
        ["yosemiterancher"]="yosemite3",
        ["yougaclassic"]="youga2",
        ["yougaclassic4x4"]="youga3",
        ["yougacustom"]="youga4",
        ["190z"]="z190",
        ["zioncabrio"]="zion2",
        ["zionclassic"]="zion3",
        ["zombiebobber"]="zombiea",
        ["zombiechopper"]="zombieb",
        ["apocalypsezr380"]="zr380",
        ["futureshockzr380"]="zr3802",
        ["nightmarezr380"]="zr3803",
        ["turismoomaggio"]="turismo3",
        ["omaggio"]="turismo3",
        ["cavalcadexl"]="cavalcade3",
        ["hellfire"]="gauntlet4",
        ["hellcat"]="gauntlet4",
        ["veyron"]="adder",
        ["chiron"]="nero",
        ["divo"]="thrax",
        ["f1"]="formula",
        ["asteropegz"]="asterope2",
        ["ballerstd"]="baller8",
        ["dominatorgt"]="dominator9",
        ["impalersz"]="imapler5",
        ["impalerlx"]="imapler6",
        ["policegauntlet"]="polgauntlet",
        ["gauntletinterceptor"]="polgauntlet",
        ["stainerlecruiser"]="police5",
        ["vigerozxconvertible"]="vigero3",
        ["oppressormk2"]="oppressor2",


        moc = "trailerlarge",
        ramp = "dune4",
        wedge = "phantom2",
        op = "oppressor",
        op1 = "oppressor",
        mk1 = "oppressor",
        op2 = "oppressor2",
        mk2 = "oppressor2",
        opressor2 = "oppressor2",
        broomstick = "oppressor2",
        b11 = "strikeforce",
        weedvan = "youga4",
        prisonbus = "pbus",
        partybus = "pbus2",
        gokart = "veto",
        antiaircraft = "trailersmall2",
        zz8 = "ruiner4",
        ingus = "ignus",
        iguns = "ignus",
        utilitytruck2 = "utillitruck2",
        utilitytruck3 = "utillitruck3",
        ["8f"] = "drafter",
        ["10fwide"] = "tenf2",
        ["10f2"] = "tenf2",
        tank = "rhino",
        egt = "omnisegt",
        donk = "faction3",
        x80 = "prototipo",
        liberator = "monster",
        f160 = "raiju",
        streamer = "streamer216",
        buffaloevx = "buffalo5",
        evx = "buffalo5",
        cliquewagon = "clique2",
        hotringhellfire = "gauntlet2",
        waltonl35 = "l35",
        walton = "l35",
        -- Thanks EndGame for additional aliases!
        d10 = "coquette4",
        xxr = "entity2",
        bug = "weevil",
        rsx = "italirsx",
        stx = "buffalo4",
        gtx = "dominator3",
        asp = "dominator7",
        gtt = "dominator8",
        dod = "dukes2",
        tank2 = "khanjali",
        tm02 = "khanjali",
        tank3 = "minitank",
        reaver = "reever",
        cabrio = "cogcabrio",
        ["370z"] = "euros",
        drag = "hakuchou2",
        ramp2 = "dune5",
        mini = "issi2",
        tb = "terbyte",
        lf22 = "starling",
        fh1 = "hunter",
        gtb = "italigtb",
        gtb2 = "italigtb2",
        xo = "torero2",
        dv8 = "deveste",
        stange = "btype2",
        valor = "btype3",
        vette = "coquette2",
        stirling = "feltzer3",
        bond = "jb700",
        bond2 = "jb7002",
        bennyspeyote = "peyote3",
        bennystornado = "tornado5",
        gogo = "blista3",
        bennyscomet = "comet3",
        bennysspecter = "specter2",
        bennysbanshee = "banshee2",
        bennysmanana = "manana2",
        bennysgtb = "italigtb2",
        bennysnero = "nero2",
        bennysdonk = "faction3",
        bennysminivan = "minivan2",
        bennyssabre = "sabregt2",
        bennysvirgo = "virgo2",
        bennysbuccaneer = "buccaneer2",
        bennyschino = "chino2",
        bennysfaction = "faction2",
        bennysvoodoo = "voodoo",
        bennysgauntlet = "gauntlet5",
        mt = "entity3",
        minirally = "issi8",
        minisport = "issi7",
        panther = "panthere",
        m100 = "tulip2",
        ver = "verlierer2",
        lacoureuse = "coureur",
        delorean = "deluxo",
    },

    VEHICLE_MAX_OPTIONS = {
        WHEEL_TYPES = 13,
        WINDOW_TINTS = 6,
    },

    VEHICLE_CLASSES = {
        COMPACTS = 0,
        SEDANS = 1,
        SUVS = 2,
        COUPES = 3,
        MUSCLE = 4,
        SPORTSCLASSICS = 5,
        SPORTS = 6,
        SUPER = 7,
        MOTORCYCLES = 8,
        OFFROAD = 9,
        INDUSTRIAL = 10,
        UTILITY = 11,
        VANS = 12,
        CYCLES = 13,
        BOATS = 14,
        HELICOPTERS = 15,
        PLANES = 16,
        SERVICE = 17,
        EMERGENCY = 18,
        MILITARY = 19,
        COMMERCIAL = 20,
        TRAINS = 21,
    },

    VEHICLE_WHEEL_TYPES = {
        STOCK = -1,
        SPORT = 0,
        MUSCLE = 1,
        LOWRIDER = 2,
        SUV = 3,
        OFFROAD = 4,
        TUNER = 5,
        BIKE = 6,
        HIGHEND = 7,
        BENNY = 8,
        BENNY2 = 9,
        F1 = 10,
        STREET = 11,
    },

    VEHICLE_PAINT_TYPES = {
        NORMAL = 0,
        METALLIC = 1,
        PEARL = 2,
        MATTE = 3,
        METAL = 4,
        CHROME = 5,
    },

    VEHICLE_MOD_TYPES = {
        MOD_SPOILER = 0,
        MOD_FRONTBUMPER = 1,
        MOD_REARBUMPER = 2,
        MOD_SIDESKIRT = 3,
        MOD_EXHAUST = 4,
        MOD_FRAME = 5, --Or roll cage
        MOD_GRILLE = 6,
        MOD_HOOD = 7,
        MOD_FENDER = 8,
        MOD_RIGHTFENDER = 9,
        MOD_ROOF = 10,
        MOD_ENGINE = 11,
        MOD_BRAKES = 12,
        MOD_TRANSMISSION = 13,
        MOD_HORNS = 14,
        MOD_SUSPENSION = 15,
        MOD_ARMOR = 16,
        MOD_UNK17 = 17,
        MOD_TURBO = 18,
        MOD_UNK19 = 19,
        MOD_TIRESMOKE = 20,
        MOD_UNK21 = 21,
        MOD_XENONLIGHTS = 22,
        MOD_FRONTWHEELS = 23,
        MOD_BACKWHEELS = 24, --Bikes only

        -- Benny's
        MOD_PLATEHOLDER = 25,
        MOD_VANITY_PLATES  = 26,
        MOD_TRIM = 27,
        MOD_ORNAMENTS = 28,
        MOD_DASHBOARD = 29,
        MOD_DIAL = 30,
        MOD_DOOR_SPEAKER = 31,
        MOD_SEATS = 32,
        MOD_STEERINGWHEEL = 33,
        MOD_SHIFTER_LEAVERS = 34,
        MOD_PLAQUES = 35,
        MOD_SPEAKERS = 36,
        MOD_TRUNK = 37,
        MOD_HYDRULICS = 38,
        MOD_ENGINE_BLOCK = 39,
        MOD_AIR_FILTER = 40,
        MOD_STRUTS = 41,
        MOD_ARCH_COVER = 42,
        MOD_AERIALS = 43,
        MOD_CHASSIS = 44,
        MOD_TANK = 45,
        MOD_WINDOWS = 46,
        MOD_UNK47 = 47,
        MOD_LIVERY = 48
    },

    VEHICLE_PLATE_TYPES = {
        MODERN = 0,
        BLACK = 1,
        BLUE = 2,
        CLASSIC = 3,
        EXEMPT = 4,
        YANKTON = 5
    },

    VEHICLE_HEADLIGHT_COLORS = {
        STOCK = -1,
        WHITE = 0,
        BLUE = 1,
        LIGHTBLUE = 2,
        GREEN = 3,
        LIME = 4,
        YELLOW = 5,
        GOLD = 6,
        ORANGE = 7,
        RED = 8,
        PINK = 9,
        HOTPINK = 10,
        PURPLE = 11,
        BLACK = 12
    },
}

constants.control_characters = {
    {1, "!"},
    {2, "?"},
    {3, "."},
    {4, "#"},
    {5, "@"},
    {6, "$"},
    {7, "%"},
    {8, "&"},
    {9, "*"},
}

constants.lobby_modes = {
    { 1, "Public", {}, "Join an existing public lobby. Will often rejoin the previous session after being dropped." },
    { 2, "New", {}, "Create a new empty public session." },
    { 3, "Join Friend", {}, "Join a friends session." },
    { 4, "Friends Only", {}, "Create a new closed friends only session." },
    { 5, "Join Crew", {}, "Create a new closed friends only session." },
}

constants.lobby_mode_commands = {
    { 1, "gopub" },
    { 2, "gosolopub" },
    { 3, "gojoinafriend" },
    { 4, "goclosedfriend" },
    { 5, "gojoinacrew" },
}

constants.headlight_color_name_map = {
    default = -1,
    white = 0,
    blue = 1,
    electricblue = 2,
    mintgreen = 3,
    green = 4,
    limegreen = 4,
    yellow = 5,
    gold = 6,
    orange = 7,
    red = 8,
    pink = 9,
    ponypink = 9,
    hotpink = 10,
    purple = 11,
    blacklight = 12
}

constants.VEHICLE_COLOR_ALIASES = {
    white='MatteWhite',
    blue='UtilBlue',
    green='UtilGreen',
    black='MetallicBlack',
    yellow='MetallicTaxiYellow',
    brown='UtilLightBrown',
    olive='MatteOliveDrab',
    orange='UtilOrange',
    pink='HotPink',
    purple='MattePurple',
}

constants.VEHICLE_COLORS = {
    {
        index=0,
        name="MetallicBlack",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#0d1116",
        rgb="13, 17, 22",
    },
    {
        index=1,
        name="MetallicGraphiteBlack",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#1c1d21",
        rgb="28, 29, 33",
        r=28,
        g=29,
        b=33,
    },
    {
        index=2,
        name="MetallicBlackSteel",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#32383d",
        rgb="50, 56, 61",
        r=50,
        g=56,
        b=61,
    },
    {
        index=3,
        name="MetallicDarkSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#454b4f",
        rgb="69, 75, 79",
        r=69,
        g=75,
        b=79,
    },
    {
        index=4,
        name="MetallicSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#999da0",
        rgb="153, 157, 160",
        r=153,
        g=157,
        b=160,
    },
    {
        index=5,
        name="MetallicBlueSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#c2c4c6",
        rgb="194, 196, 198",
        r=194,
        g=196,
        b=198,
    },
    {
        index=6,
        name="MetallicSteelGray",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#979a97",
        rgb="151, 154, 151",
        r=151,
        g=154,
        b=151,
    },
    {
        index=7,
        name="MetallicShadowSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#637380",
        rgb="99, 115, 128",
        r=99,
        g=115,
        b=128,
    },
    {
        index=8,
        name="MetallicStoneSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#63625c",
        rgb="99, 98, 92",
        r=99,
        g=98,
        b=92,
    },
    {
        index=9,
        name="MidnightSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#3c3f47",
        rgb="60, 63, 71",
        r=60,
        g=63,
        b=71,
    },
    {
        index=10,
        name="MetallicGunMetal",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#444e54",
        rgb="68, 78, 84",
        r=68,
        g=78,
        b=84,
    },
    {
        index=11,
        name="AnthraciteGrey",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#1d2129",
        rgb="29, 33, 41",
        r=29,
        g=33,
        b=41,
    },
    {
        index=12,
        name="MatteBlack",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#13181f",
        rgb="19, 24, 31",
        r=19,
        g=24,
        b=31,
    },
    {
        index=13,
        name="MatteGray",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#26282a",
        rgb="38, 40, 42",
        r=38,
        g=40,
        b=42,
    },
    {
        index=14,
        name="MatteLightGrey",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#515554",
        rgb="81, 85, 84",
        r=81,
        g=85,
        b=84,
    },
    {
        index=15,
        name="UtilBlack",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#151921",
        rgb="21, 25, 33",
        r=21,
        g=25,
        b=33,
    },
    {
        index=16,
        name="UtilBlackPoly",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#1e2429",
        rgb="30, 36, 41",
        r=30,
        g=36,
        b=41,
    },
    {
        index=17,
        name="NormalDarkSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#333a3c",
        rgb="51, 58, 60",
        r=51,
        g=58,
        b=60,
    },
    {
        index=18,
        name="NormalSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#8c9095",
        rgb="140, 144, 149",
        r=140,
        g=144,
        b=149,
    },
    {
        index=19,
        name="NormalGunMetal",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#39434d",
        rgb="57, 67, 77",
        r=57,
        g=67,
        b=77,
    },
    {
        index=20,
        name="NormalShadowSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#506272",
        rgb="80, 98, 114",
        r=80,
        g=98,
        b=114,
    },
    {
        index=21,
        name="WornBlack",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#1e232f",
        rgb="30, 35, 47",
        r=30,
        g=35,
        b=47,
    },
    {
        index=22,
        name="WornGraphite",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#363a3f",
        rgb="54, 58, 63",
        r=54,
        g=58,
        b=63,
    },
    {
        index=23,
        name="WornSilverGrey",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#a0a199",
        rgb="160, 161, 153",
        r=160,
        g=161,
        b=153,
    },
    {
        index=24,
        name="WornSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#d3d3d3",
        rgb="211, 211, 211",
        r=211,
        g=211,
        b=211,
    },
    {
        index=25,
        name="WornBlueSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#b7bfca",
        rgb="183, 191, 202",
        r=183,
        g=191,
        b=202,
    },
    {
        index=26,
        name="WornShadowSilver",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#778794",
        rgb="119, 135, 148",
        r=119,
        g=135,
        b=148,
    },
    {
        index=27,
        name="MetallicRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#c00e1a",
        rgb="192, 14, 26",
        r=192,
        g=14,
        b=26,
    },
    {
        index=28,
        name="MetallicTorinoRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#da1918",
        rgb="218, 25, 24",
        r=218,
        g=25,
        b=24,
    },
    {
        index=29,
        name="MetallicFormulaRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#b6111b",
        rgb="182, 17, 27",
        r=182,
        g=17,
        b=27,
    },
    {
        index=30,
        name="MetallicBlazeRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#a51e23",
        rgb="165, 30, 35",
        r=165,
        g=30,
        b=35,
    },
    {
        index=31,
        name="MetallicGracefulRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#7b1a22",
        rgb="123, 26, 34",
        r=123,
        g=26,
        b=34,
    },
    {
        index=32,
        name="MetallicGarnetRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#8e1b1f",
        rgb="142, 27, 31",
        r=142,
        g=27,
        b=31,
    },
    {
        index=33,
        name="MetallicDesertRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#6f1818",
        rgb="111, 24, 24",
        r=111,
        g=24,
        b=24,
    },
    {
        index=34,
        name="MetallicCabernetRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#49111d",
        rgb="73, 17, 29",
        r=73,
        g=17,
        b=29,
    },
    {
        index=35,
        name="MetallicCandyRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#b60f25",
        rgb="182, 15, 37",
        r=182,
        g=15,
        b=37,
    },
    {
        index=36,
        name="MetallicSunriseOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#d44a17",
        rgb="212, 74, 23",
        r=212,
        g=74,
        b=23,
    },
    {
        index=37,
        name="MetallicClassicGold",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#c2944f",
        rgb="194, 148, 79",
        r=194,
        g=148,
        b=79,
    },
    {
        index=38,
        name="MetallicOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#f78616",
        rgb="247, 134, 22",
        r=247,
        g=134,
        b=22,
    },
    {
        index=39,
        name="MatteRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#cf1f21",
        rgb="207, 31, 33",
        r=207,
        g=31,
        b=33,
    },
    {
        index=40,
        name="MatteDarkRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#732021",
        rgb="115, 32, 33",
        r=115,
        g=32,
        b=33,
    },
    {
        index=41,
        name="MatteOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#f27d20",
        rgb="242, 125, 32",
        r=242,
        g=125,
        b=32,
    },
    {
        index=42,
        name="MatteYellow",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#ffc91f",
        rgb="255, 201, 31",
        r=255,
        g=201,
        b=31,
    },
    {
        index=43,
        name="Red",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#9c1016",
        rgb="156, 16, 22",
        r=156,
        g=16,
        b=22,
    },
    {
        index=44,
        name="UtilBrightRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#de0f18",
        rgb="222, 15, 24",
        r=222,
        g=15,
        b=24,
    },
    {
        index=45,
        name="UtilGarnetRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#8f1e17",
        rgb="143, 30, 23",
        r=143,
        g=30,
        b=23,
    },
    {
        index=46,
        name="WornRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#a94744",
        rgb="169, 71, 68",
        r=169,
        g=71,
        b=68,
    },
    {
        index=47,
        name="WornGoldenRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#b16c51",
        rgb="177, 108, 81",
        r=177,
        g=108,
        b=81,
    },
    {
        index=48,
        name="WornDarkRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#371c25",
        rgb="55, 28, 37",
        r=55,
        g=28,
        b=37,
    },
    {
        index=49,
        name="MetallicDarkGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#132428",
        rgb="19, 36, 40",
        r=19,
        g=36,
        b=40,
    },
    {
        index=50,
        name="MetallicRacingGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#122e2b",
        rgb="18, 46, 43",
        r=18,
        g=46,
        b=43,
    },
    {
        index=51,
        name="MetallicSeaGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#12383c",
        rgb="18, 56, 60",
        r=18,
        g=56,
        b=60,
    },
    {
        index=52,
        name="MetallicOliveGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#31423f",
        rgb="49, 66, 63",
        r=49,
        g=66,
        b=63,
    },
    {
        index=53,
        name="MetallicGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#155c2d",
        rgb="21, 92, 45",
        r=21,
        g=92,
        b=45,
    },
    {
        index=54,
        name="MetallicGasolineBlueGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#1b6770",
        rgb="27, 103, 112",
        r=27,
        g=103,
        b=112,
    },
    {
        index=55,
        name="MatteLimeGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#66b81f",
        rgb="102, 184, 31",
        r=102,
        g=184,
        b=31,
    },
    {
        index=56,
        name="UtilDarkGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#22383e",
        rgb="34, 56, 62",
        r=34,
        g=56,
        b=62,
    },
    {
        index=57,
        name="UtilGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#1d5a3f",
        rgb="29, 90, 63",
        r=29,
        g=90,
        b=63,
    },
    {
        index=58,
        name="WornDarkGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#2d423f",
        rgb="45, 66, 63",
        r=45,
        g=66,
        b=63,
    },
    {
        index=59,
        name="WornGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#45594b",
        rgb="69, 89, 75",
        r=69,
        g=89,
        b=75,
    },
    {
        index=60,
        name="WornSeaWash",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#65867f",
        rgb="101, 134, 127",
        r=101,
        g=134,
        b=127,
    },
    {
        index=61,
        name="MetallicMidnightBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#222e46",
        rgb="34, 46, 70",
        r=34,
        g=46,
        b=70,
    },
    {
        index=62,
        name="MetallicDarkBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#233155",
        rgb="35, 49, 85",
        r=35,
        g=49,
        b=85,
    },
    {
        index=63,
        name="MetallicSaxonyBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#304c7e",
        rgb="48, 76, 126",
        r=48,
        g=76,
        b=126,
    },
    {
        index=64,
        name="MetallicBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#47578f",
        rgb="71, 87, 143",
        r=71,
        g=87,
        b=143,
    },
    {
        index=65,
        name="MetallicMarinerBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#637ba7",
        rgb="99, 123, 167",
        r=99,
        g=123,
        b=167,
    },
    {
        index=66,
        name="MetallicHarborBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#394762",
        rgb="57, 71, 98",
        r=57,
        g=71,
        b=98,
    },
    {
        index=67,
        name="MetallicDiamondBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#d6e7f1",
        rgb="214, 231, 241",
        r=214,
        g=231,
        b=241,
    },
    {
        index=68,
        name="MetallicSurfBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#76afbe",
        rgb="118, 175, 190",
        r=118,
        g=175,
        b=190,
    },
    {
        index=69,
        name="MetallicNauticalBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#345e72",
        rgb="52, 94, 114",
        r=52,
        g=94,
        b=114,
    },
    {
        index=70,
        name="MetallicBrightBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#0b9cf1",
        rgb="11, 156, 241",
        r=11,
        g=156,
        b=241,
    },
    {
        index=71,
        name="MetallicPurpleBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#2f2d52",
        rgb="47, 45, 82",
        r=47,
        g=45,
        b=82,
    },
    {
        index=72,
        name="MetallicSpinnakerBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#282c4d",
        rgb="40, 44, 77",
        r=40,
        g=44,
        b=77,
    },
    {
        index=73,
        name="MetallicUltraBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#2354a1",
        rgb="35, 84, 161",
        r=35,
        g=84,
        b=161,
    },
    {
        index=74,
        name="MetallicBrightBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#6ea3c6",
        rgb="110, 163, 198",
        r=110,
        g=163,
        b=198,
    },
    {
        index=75,
        name="UtilDarkBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#112552",
        rgb="17, 37, 82",
        r=17,
        g=37,
        b=82,
    },
    {
        index=76,
        name="UtilMidnightBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#1b203e",
        rgb="27, 32, 62",
        r=27,
        g=32,
        b=62,
    },
    {
        index=77,
        name="UtilBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#275190",
        rgb="39, 81, 144",
        r=39,
        g=81,
        b=144,
    },
    {
        index=78,
        name="UtilSeaFoamBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#608592",
        rgb="96, 133, 146",
        r=96,
        g=133,
        b=146,
    },
    {
        index=79,
        name="UtilLightningblue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#2446a8",
        rgb="36, 70, 168",
        r=36,
        g=70,
        b=168,
    },
    {
        index=80,
        name="UtilMauiBluePoly",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#4271e1",
        rgb="66, 113, 225",
        r=66,
        g=113,
        b=225,
    },
    {
        index=81,
        name="UtilBrightBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#3b39e0",
        rgb="59, 57, 224",
        r=59,
        g=57,
        b=224,
    },
    {
        index=82,
        name="MatteDarkBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#1f2852",
        rgb="31, 40, 82",
        r=31,
        g=40,
        b=82,
    },
    {
        index=83,
        name="MatteBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#253aa7",
        rgb="37, 58, 167",
        r=37,
        g=58,
        b=167,
    },
    {
        index=84,
        name="MatteMidnightBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#1c3551",
        rgb="28, 53, 81",
        r=28,
        g=53,
        b=81,
    },
    {
        index=85,
        name="WornDarkblue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#4c5f81",
        rgb="76, 95, 129",
        r=76,
        g=95,
        b=129,
    },
    {
        index=86,
        name="WornBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#58688e",
        rgb="88, 104, 142",
        r=88,
        g=104,
        b=142,
    },
    {
        index=87,
        name="WornLightblue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#74b5d8",
        rgb="116, 181, 216",
        r=116,
        g=181,
        b=216,
    },
    {
        index=88,
        name="MetallicTaxiYellow",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#ffcf20",
        rgb="255, 207, 32",
        r=255,
        g=207,
        b=32,
    },
    {
        index=89,
        name="MetallicRaceYellow",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#fbe212",
        rgb="251, 226, 18",
        r=251,
        g=226,
        b=18,
    },
    {
        index=90,
        name="MetallicBronze",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#916532",
        rgb="145, 101, 50",
        r=145,
        g=101,
        b=50,
    },
    {
        index=91,
        name="MetallicYellowBird",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#e0e13d",
        rgb="224, 225, 61",
        r=224,
        g=225,
        b=61,
    },
    {
        index=92,
        name="MetallicLime",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#98d223",
        rgb="152, 210, 35",
        r=152,
        g=210,
        b=35,
    },
    {
        index=93,
        name="MetallicChampagne",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#9b8c78",
        rgb="155, 140, 120",
        r=155,
        g=140,
        b=120,
    },
    {
        index=94,
        name="MetallicPuebloBeige",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#503218",
        rgb="80, 50, 24",
        r=80,
        g=50,
        b=24,
    },
    {
        index=95,
        name="MetallicDarkIvory",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#473f2b",
        rgb="71, 63, 43",
        r=71,
        g=63,
        b=43,
    },
    {
        index=96,
        name="MetallicChocoBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#221b19",
        rgb="34, 27, 25",
        r=34,
        g=27,
        b=25,
    },
    {
        index=97,
        name="MetallicGoldenBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#653f23",
        rgb="101, 63, 35",
        r=101,
        g=63,
        b=35,
    },
    {
        index=98,
        name="MetallicLightBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#775c3e",
        rgb="119, 92, 62",
        r=119,
        g=92,
        b=62,
    },
    {
        index=99,
        name="MetallicStrawBeige",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#ac9975",
        rgb="172, 153, 117",
        r=172,
        g=153,
        b=117,
    },
    {
        index=100,
        name="MetallicMossBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#6c6b4b",
        rgb="108, 107, 75",
        r=108,
        g=107,
        b=75,
    },
    {
        index=101,
        name="MetallicBistonBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#402e2b",
        rgb="64, 46, 43",
        r=64,
        g=46,
        b=43,
    },
    {
        index=102,
        name="MetallicBeechwood",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#a4965f",
        rgb="164, 150, 95",
        r=164,
        g=150,
        b=95,
    },
    {
        index=103,
        name="MetallicDarkBeechwood",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#46231a",
        rgb="70, 35, 26",
        r=70,
        g=35,
        b=26,
    },
    {
        index=104,
        name="MetallicChocoOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#752b19",
        rgb="117, 43, 25",
        r=117,
        g=43,
        b=25,
    },
    {
        index=105,
        name="MetallicBeachSand",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#bfae7b",
        rgb="191, 174, 123",
        r=191,
        g=174,
        b=123,
    },
    {
        index=106,
        name="MetallicSunBleechedSand",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#dfd5b2",
        rgb="223, 213, 178",
        r=223,
        g=213,
        b=178,
    },
    {
        index=107,
        name="MetallicCream",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#f7edd5",
        rgb="247, 237, 213",
        r=247,
        g=237,
        b=213,
    },
    {
        index=108,
        name="UtilBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#3a2a1b",
        rgb="58, 42, 27",
        r=58,
        g=42,
        b=27,
    },
    {
        index=109,
        name="UtilMediumBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#785f33",
        rgb="120, 95, 51",
        r=120,
        g=95,
        b=51,
    },
    {
        index=110,
        name="UtilLightBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#b5a079",
        rgb="181, 160, 121",
        r=181,
        g=160,
        b=121,
    },
    {
        index=111,
        name="MetallicWhite",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#fffff6",
        rgb="255, 255, 246",
        r=255,
        g=255,
        b=246,
    },
    {
        index=112,
        name="MetallicFrostWhite",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#eaeaea",
        rgb="234, 234, 234",
        r=234,
        g=234,
        b=234,
    },
    {
        index=113,
        name="WornHoneyBeige",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#b0ab94",
        rgb="176, 171, 148",
        r=176,
        g=171,
        b=148,
    },
    {
        index=114,
        name="WornBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#453831",
        rgb="69, 56, 49",
        r=69,
        g=56,
        b=49,
    },
    {
        index=115,
        name="WornDarkBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#2a282b",
        rgb="42, 40, 43",
        r=42,
        g=40,
        b=43,
    },
    {
        index=116,
        name="Wornstrawbeige",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#726c57",
        rgb="114, 108, 87",
        r=114,
        g=108,
        b=87,
    },
    {
        index=117,
        name="BrushedSteel",
        paint_type=constants.VEHICLE_PAINT_TYPES.METAL,
        hex="#6a747c",
        rgb="106, 116, 124",
        r=106,
        g=116,
        b=124,
    },
    {
        index=118,
        name="BrushedBlacksteel",
        paint_type=constants.VEHICLE_PAINT_TYPES.METAL,
        hex="#354158",
        rgb="53, 65, 88",
        r=53,
        g=65,
        b=88,
    },
    {
        index=119,
        name="BrushedAluminium",
        paint_type=constants.VEHICLE_PAINT_TYPES.METAL,
        hex="#9ba0a8",
        rgb="155, 160, 168",
        r=155,
        g=160,
        b=168,
    },
    {
        index=120,
        name="Chrome",
        paint_type=constants.VEHICLE_PAINT_TYPES.METAL,
        hex="#5870a1",
        rgb="88, 112, 161",
        r=88,
        g=112,
        b=161,
    },
    {
        index=121,
        name="WornOffWhite",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#eae6de",
        rgb="234, 230, 222",
        r=234,
        g=230,
        b=222,
    },
    {
        index=122,
        name="UtilOffWhite",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#dfddd0",
        rgb="223, 221, 208",
        r=223,
        g=221,
        b=208,
    },
    {
        index=123,
        name="WornOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#f2ad2e",
        rgb="242, 173, 46",
        r=242,
        g=173,
        b=46,
    },
    {
        index=124,
        name="WornLightOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#f9a458",
        rgb="249, 164, 88",
        r=249,
        g=164,
        b=88,
    },
    {
        index=125,
        name="MetallicSecuricorGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#83c566",
        rgb="131, 197, 102",
        r=131,
        g=197,
        b=102,
    },
    {
        index=126,
        name="WornTaxiYellow",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#f1cc40",
        rgb="241, 204, 64",
        r=241,
        g=204,
        b=64,
    },
    {
        index=127,
        name="PoliceCarBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#4cc3da",
        rgb="76, 195, 218",
        r=76,
        g=195,
        b=218,
    },
    {
        index=128,
        name="MatteGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#4e6443",
        rgb="78, 100, 67",
        r=78,
        g=100,
        b=67,
    },
    {
        index=129,
        name="MatteBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#bcac8f",
        rgb="188, 172, 143",
        r=188,
        g=172,
        b=143,
    },
    {
        index=130,
        name="WornOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#f8b658",
        rgb="248, 182, 88",
        r=248,
        g=182,
        b=88,
    },
    {
        index=131,
        name="MatteWhite",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#fcf9f1",
        rgb="252, 249, 241",
        r=252,
        g=249,
        b=241,
    },
    {
        index=132,
        name="WornWhite",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#fffffb",
        rgb="255, 255, 251",
        r=255,
        g=255,
        b=251,
    },
    {
        index=133,
        name="WornOliveArmyGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#81844c",
        rgb="129, 132, 76",
        r=129,
        g=132,
        b=76,
    },
    {
        index=134,
        name="PureWhite",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#ffffff",
        rgb="255, 255, 255",
        r=255,
        g=255,
        b=255,
    },
    {
        index=135,
        name="HotPink",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#f21f99",
        rgb="242, 31, 153",
        r=242,
        g=31,
        b=153,
    },
    {
        index=136,
        name="SalmonPink",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#fdd6cd",
        rgb="253, 214, 205",
        r=253,
        g=214,
        b=205,
    },
    {
        index=137,
        name="MetallicVermillionPink",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#df5891",
        rgb="223, 88, 145",
        r=223,
        g=88,
        b=145,
    },
    {
        index=138,
        name="UtilOrange",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#f6ae20",
        rgb="246, 174, 32",
        r=246,
        g=174,
        b=32,
    },
    {
        index=139,
        name="UtilGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#b0ee6e",
        rgb="176, 238, 110",
        r=176,
        g=238,
        b=110,
    },
    {
        index=140,
        name="UtilBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#08e9fa",
        rgb="8, 233, 250",
        r=8,
        g=233,
        b=250,
    },
    {
        index=141,
        name="MettalicBlackBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#0a0c17",
        rgb="10, 12, 23",
        r=10,
        g=12,
        b=23,
    },
    {
        index=142,
        name="MetallicBlackPurple",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#0c0d18",
        rgb="12, 13, 24",
        r=12,
        g=13,
        b=24,
    },
    {
        index=143,
        name="MetallicBlackRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#0e0d14",
        rgb="14, 13, 20",
        r=14,
        g=13,
        b=20,
    },
    {
        index=144,
        name="HunterGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#9f9e8a",
        rgb="159, 158, 138",
        r=159,
        g=158,
        b=138,
    },
    {
        index=145,
        name="MetallicPurple",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#621276",
        rgb="98, 18, 118",
        r=98,
        g=18,
        b=118,
    },
    {
        index=146,
        name="MetaillicVDarkBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#0b1421",
        rgb="11, 20, 33",
        r=11,
        g=20,
        b=33,
    },
    {
        index=147,
        name="ModShopBlack",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#11141a",
        rgb="17, 20, 26",
        r=17,
        g=20,
        b=26,
    },
    {
        index=148,
        name="MattePurple",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#6b1f7b",
        rgb="107, 31, 123",
        r=107,
        g=31,
        b=123,
    },
    {
        index=149,
        name="MatteDarkPurple",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#1e1d22",
        rgb="30, 29, 34",
        r=30,
        g=29,
        b=34,
    },
    {
        index=150,
        name="MetallicLavaRed",
        paint_type=constants.VEHICLE_PAINT_TYPES.METALLIC,
        hex="#bc1917",
        rgb="188, 25, 23",
        r=188,
        g=25,
        b=23,
    },
    {
        index=151,
        name="MatteForestGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#2d362a",
        rgb="45, 54, 42",
        r=45,
        g=54,
        b=42,
    },
    {
        index=152,
        name="MatteOliveDrab",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#696748",
        rgb="105, 103, 72",
        r=105,
        g=103,
        b=72,
    },
    {
        index=153,
        name="MatteDesertBrown",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#7a6c55",
        rgb="122, 108, 85",
        r=122,
        g=108,
        b=85,
    },
    {
        index=154,
        name="MatteDesertTan",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#c3b492",
        rgb="195, 180, 146",
        r=195,
        g=180,
        b=146,
    },
    {
        index=155,
        name="MatteFoilageGreen",
        paint_type=constants.VEHICLE_PAINT_TYPES.MATTE,
        hex="#5a6352",
        rgb="90, 99, 82",
        r=90,
        g=99,
        b=82,
    },
    {
        index=156,
        name="DEFAULTALLOYCOLOR",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#81827f",
        rgb="129, 130, 127",
        r=129,
        g=130,
        b=127,
    },
    {
        index=157,
        name="EpsilonBlue",
        paint_type=constants.VEHICLE_PAINT_TYPES.NORMAL,
        hex="#afd6e4",
        rgb="175, 214, 228",
        r=175,
        g=214,
        b=228,
    },
    {
        index=158,
        name="PureGold",
        paint_type=constants.VEHICLE_PAINT_TYPES.METAL,
        hex="#7a6440",
        rgb="122, 100, 64",
        r=122,
        g=100,
        b=64,
    },
    {
        index=159,
        name="BrushedGold",
        paint_type=constants.VEHICLE_PAINT_TYPES.METAL,
        hex="#7f6a48",
        rgb="127, 106, 72",
        r=127,
        g=106,
        b=72,
    },
}


return constants
